name: CI/CD Pipeline - CloudPlay

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/tic-tac-toe
            git pull origin main

            # Backend - FastAPI
            cd Server
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo systemctl restart tictactoe

            # Frontend - React
            cd /home/ubuntu/tic-tac-toe/frontend
            npm install
            npm run build
            echo "Deployment successful! ✅"